homework_reminders/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))

]

main/urls.py
from django.urls import path
from main.views import add_product_ajax, get_product_json, show_main
from main.views import register #sesuaikan dengan nama fungsi yang dibuat
from main.views import login_user
from main.views import logout_user, add_amount, decrement_amount, delete_product
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import get_product_json, add_product_ajax, edit_product_ajax
from main.views import show_json_by_user, show_xml_by_user, edit_product, create_product_flutter
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('json-by-user/', show_json_by_user, name='show_json_by_user'),
    path('xml-by-user/', show_xml_by_user, name='show_xml_by_user'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increase-product-amount/<int:id>/', add_amount, name='add_amount'),
    path('decrement-product-amount/<int:id>/', decrement_amount, name='decrement_amount'),
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('edit-product/<int:id>/', edit_product, name='edit_product'),
    path('edit-product-ajax/<int:id>/', edit_product_ajax, name='edit_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    ]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id: int):
    data = Product.objects.filter(pk=id)
    print(data)
    return HttpResponse(serializers.serialize('xml', data), content_type='application/xml')

def show_json_by_id(request, id: int):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
    'name': request.user.username,
    'class': 'PBP A',
    'products': products,
    'last_login': request.COOKIES['last_login'],
}

    return render(request, "main.html", context)

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, "create_product.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_amount(request, product_id):
    products = Product.objects.filter(user=request.user)

    context = {
    'name': request.user.username,
    'class': 'PBP A',
    'products': products,
    'last_login': request.COOKIES['last_login'],
    }

    if request.method == 'POST':
        product = get_object_or_404(Product, pk=product_id)
        
        product.amount += 1
        product.save()

    return render(request, "main.html", context)

@csrf_exempt
def decrement_amount(request, id):
    current_product = Product.objects.get(pk=id)
    current_product.amount -= 1
    if current_product.amount == 0 :
        return delete_product(request, id)
    current_product.save()
    return HttpResponse(b"DECREMENTED PRODUCT SUCCESSFULLY", status=200)


@csrf_exempt
def delete_product(request, id):
    if request.method == 'DELETE':
        current_product = Product.objects.get(pk=id)
        current_product.delete()
        return HttpResponse(b"DELETED PRODUCT SUCCESSFULLY", status=200)
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def add_amount(request, id):
    current_product = Product.objects.get(pk=id)
    current_product.amount += 1
    current_product.save()
    return HttpResponse(b"ADDED PRODUCT SUCCESSFULLY", status=200)

@csrf_exempt
def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)


def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def edit_product_ajax(request, id):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, amount=amount, description=description, user=user)
        product = Product.objects.get(pk=id)
        product = new_product
        product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@login_required(login_url='/login')  
def show_json_by_user(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')  
def show_xml_by_user(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            description = data["description"],
            amount = data["amount"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<style>
    .form-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .form-container h1 {
        font-size: 24px;
        text-align: center;
    }



    .form-container form {
        text-align: center;
    }

    .form-container table {
        margin: 0 auto;
    }

    .form-container input[type="text"],
    .form-container input[type="number"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .form-container input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .form-container input[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>

<div class="form-container">
    <h1>Add New Product</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Product"/>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1>Edit Product</h1>

    <form method="POST" class="mt-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.name.id_for_label }}" class="form-label">Product Name</label>
            {{ form.name }}
        </div>

        <div class="mb-3">
            <label for="{{ form.price.id_for_label }}" class="form-label">Price</label>
            {{ form.price }}
        </div>

        <div class="mb-3">
            <label for="{{ form.amount.id_for_label }}" class="form-label">Amount</label>
            {{ form.amount }}
        </div>

        <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
            {{ form.description }}
        </div>

        <button type="submit" class="btn btn-primary">Edit Product</button>
    </form>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homework Reminder Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 24px;
            color: #333;
        }

        h5 {
            font-size: 16px;
            color: #777;
        }

        p {
            font-size: 16px;
            color: #333;
        }

        /* Style the table */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        table tr:nth-child(even) {
            background-color: #f5f5f5;
        }
        button {
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
        a button {
            margin-top: 20px;
            background-color: #28a745;
        }

        a button:hover {
            background-color: #1e7e34;
        }

        table tr:last-child {
            background-color: #ffcccc; 
        }
    </style>
</head>
<body>
    <h1>Homework Reminder Page</h1>
    
    <div class="row" id="product_cards"></div>
    
    <br />

    <a href="{% url 'main:create_product' %}">
        <button>
            Add New Product
        </button>
    </a>

    <br />

    <h5>Sesi terakhir login: {{ last_login }}</h5>

    <a href="{% url 'main:logout' %}">
        <button>
            Logout
        </button>
    </a>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

    <h2>Nama:</h2>
    <p>{{ name }}</p>

    <h2>Class:</h2>
    <p>{{ class }}</p>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form-add" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
<script>
    function addProduct() {
        fetch("/create-product-ajax/", {
            method: "POST",
            body: new FormData(document.querySelector('#form-add'))
        }).then(refreshProducts)

        document.getElementById("form-add").reset()
        return false
        }

        async function getProducts() {
        return fetch("/get-product/").then((res) => res.json())
        }

        async function getProductById(idProduct) {
        const listProducts = await getProducts()
        return listProducts.find(product => product.pk === idProduct)
        }

        async function increaseProductAmount(idProduct) {
        await fetch(`/increase-product-amount/${idProduct}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({}),
        });
        refreshProductAmount(idProduct);
        }

        async function decrementProductAmount(idProduct) {
        await fetch(`/decrement-product-amount/${idProduct}/`, {
            method: 'POST',
            body: JSON.stringify({}),
        });
        refreshProductAmount(idProduct);
        }

        async function deleteProduct(idProduct) {
        await fetch(`/delete-product/${idProduct}/`, {
            method: 'DELETE',
            body: JSON.stringify({}),
        });
        refreshProducts()
        }

        async function refreshProductAmount(idProduct){
        const product = await getProductById(idProduct);
        const amountHTML = document.getElementById(`amount-${idProduct}`)

        amountHTML.innerHTML = `Jumlah: ${product.fields.amount}`
        }

        async function refreshProducts(){
        document.getElementById("product_cards").innerHTML = ""
        const products = await getProducts()
        let htmlString = ""
        products.forEach((product, index) =>{
            htmlString += `\n<div class="col-lg-4 col-md-6 mb-4">
                <div id="${product.pk}" class="card h-100 ${index === products.length - 1 ? `last-product` : ``}">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">${product.fields.name}</h5>
                        <div class="button-group">
                            <button class="btn btn-sm cust-button" onclick="increaseProductAmount(${product.pk})">+</button>
                            <button class="btn btn-sm cust-button" onclick="decrementProductAmount(${product.pk})">-</button>
                            <button class="btn btn-sm delete-button" onclick="deleteProduct(${product.pk})">Delete</button>
                            <a href="/edit-product/${product.pk}/"><button class="btn btn-sm edit-button">Edit</button></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="text-muted small" id="amount-${product.pk}">Jumlah: ${product.fields.amount}</p>
                        <p class="card-text">${product.fields.description}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Added on: ${product.fields.date_added}</small>
                    </div>
                </div>
            </div>`
        })
        document.getElementById("product_cards").innerHTML = htmlString
        }

        refreshProducts()
        document.getElementById("button_add").onclick = addProduct
</script>
    
  {% endblock content %}